### ISSUE TITLE
users mapping spreadsheet

### ISSUE THREAD

**Issue by ryanmax** [sul-dlss/folio-lane-migration#7]
Complete IndexData's[ user mapping spreadsheet](https://docs.google.com/spreadsheets/d/1rb8UyAWeYwNNMhWMQJ_r-gzrSTjkw-d-2D5Ip8Cl8xE)

**Comment by jgreben** [comment]
ID never loaded users for Lane. We loaded them and Lane created the rest of the user records manually.
